export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  script: "https://kit.fontawesome.com/b935e69800.js"
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/b935e69800.js" crossOrigin="anonymous"></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
